ALTER TABLE feedback ADD COLUMN admin_note TEXT;
ALTER TABLE feedback ADD COLUMN updated_at TEXT;
CREATE TABLE IF NOT EXISTS feedback_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id INTEGER NOT NULL, actor_id INTEGER NOT NULL, action TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(feedback_id) REFERENCES feedback(id) ON DELETE CASCADE);
