ALTER TABLE data_sources ADD COLUMN enabled INTEGER NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS source_admin_history (id INTEGER PRIMARY KEY AUTOINCREMENT, source_id TEXT NOT NULL, actor_id INTEGER NOT NULL, action TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS technical_errors (id INTEGER PRIMARY KEY AUTOINCREMENT, component TEXT NOT NULL, error_code TEXT NOT NULL, level TEXT NOT NULL, message TEXT NOT NULL, resolved INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
